basic_settings:
  site_title: YJ
  favicon_image: /img/favicon.ico

header_settings:
  logo_image: 
  logo_width: 200
  
hero_settings:
  background_image: /img/backgrounds/banner.png

menu_settings:
  menu_items:
    - title: 'Works'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about'

footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline:


grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 12

contact_settings:
  form_action: 'https://formspree.io/your@email.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/yujiin.leee'
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: 'https://dribbble.com/yujiinlee'
  behance_url: 'https://www.behance.net/yujiinlee'
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/yujin-lee-811640131/'

color_settings:
  background_color: '#fff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#3E4056'
  text_light_color: '#ABB7B7'
  accent_color: '#4A5AE2'
  border_color: '#dddddd'
  overlay_background_color: '#fff'
  overlay_text_color: '#2A2F36'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,700,900|Source+Sans+Pro:400,500,700,900" rel="stylesheet">'
  title_font: '"Source Code Pro", monospace;'
  body_font: '"Spoqa Han Sans", "Spoqa Han Sans JP", sans-serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 20
    medium_size: 25
    large_size: 30
    weight: 500
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 400
    letter_spacing: 0
  grid_item_title:
    small_size: 18
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 8
    medium_size: 12
    large_size: 15
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 28
    medium_size: 32
    large_size: 40
    weight: 700
    letter_spacing: -0.02
    line_height: 1.5
  h2:
    small_size: 24
    medium_size: 28
    large_size: 32
    weight: 700
    letter_spacing: 0
    line_height: 1.5
  h3:
    small_size: 18
    medium_size: 20
    large_size: 24
    weight: 600
    letter_spacing: -0.02
    line_height: 1.6
  h4:
    small_size: 18
    medium_size: 20
    large_size: 24
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 18
    medium_size: 20
    large_size: 24
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 13
    medium_size: 15
    large_size: 17
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 19
    large_size: 19
    weight: 400
    letter_spacing:
    line_height: 1.8
  blockquote:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""